name: Continous Integration

# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        node-version: [12]
        include:
          - os: ubuntu-latest
            node-version: 10
          - os: ubuntu-latest
            node-version: 14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update NPM
        run: npm i -g npm
      - name: Bootstrap project
        run: npm ci --ignore-scripts
        env:
          CI: true
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm run test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Update NPM
        run: npm i -g npm
      - name: Bootstrap project
        run: npm ci --ignore-scripts
        env:
          CI: true
      - name: Build project
        run: npm run build
      - name: Check linting
        run: npm run lint
